# 生产环境配置
database:
  host: "${DB_HOST:localhost}"
  port: "${DB_PORT:5432}"
  name: "${DB_NAME:aintegration}"
  user: "${DB_USER:postgres}"
  password: "${DB_PASSWORD}"
  pool_size: 20
  max_overflow: 50

redis:
  host: "${REDIS_HOST:localhost}"
  port: "${REDIS_PORT:6379}"
  db: "${REDIS_DB:0}"
  password: "${REDIS_PASSWORD}"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/aintegration/aintegration.log"

mcp_server:
  host: "${MCP_HOST:localhost}"
  port: "${MCP_PORT:8004}"
  protocol: "http"

a2a_server:
  host: "${A2A_HOST:localhost}"
  port: "${A2A_PORT:8005}"
  protocol: "a2a"

google_adk:
  api_key: "${GOOGLE_API_KEY}"
  model: "gemini-pro"
  
agents:
  hr_agent:
    system_prompt: "你是一个HR系统的专业代理，负责处理员工相关的所有操作"
    allowed_tools: ["create_employee", "update_employee", "get_employee_info"]
    
  finance_agent:
    system_prompt: "你是一个财务系统的专业代理，负责处理财务相关的所有操作"
    allowed_tools: ["enroll_payroll", "create_payroll_account"]
    
  it_agent:
    system_prompt: "你是一个IT系统的专业代理，负责处理IT相关的所有操作"
    allowed_tools: ["apply_computer", "create_user_account"]
    
  inventory_agent:
    system_prompt: "你是一个库存系统的专业代理，负责处理库存相关的所有操作"
    allowed_tools: ["outbound", "check_outbound_status"]
    
  access_agent:
    system_prompt: "你是一个门禁系统的专业代理，负责处理门禁相关的所有操作"
    allowed_tools: ["grant_access", "create_access_card"]

api:
  host: "0.0.0.0"
  port: "${API_PORT:8000}"
  title: "AIntegration API"
  description: "企业集成代理框架API"
  version: "1.0.0"

security:
  secret_key: "${SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 30
